// This file is auto-generated by `npm run db:types`.
// Run that command after applying the migration to populate it.
// Until then, this minimal stub keeps the project compilable.

export type Database = {
  public: {
    Tables: Record<string, { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }>;
    Views: Record<string, never>;
    Functions: Record<string, { Args: Record<string, unknown>; Returns: unknown }>;
    Enums: Record<string, string>;
  };
};
