/**
 * supabase-extended.types.ts
 *
 * Minimal residual types that cannot be generated by `supabase gen types`:
 *   - Custom RPC return shapes (RPCs return `Json` in the generated types —
 *     callers must cast to a concrete shape after an error check).
 *   - RPC argument wrappers for RPCs defined in migrations.
 *
 * All table Insert/Update/Row types are now in database.types.ts (TYPE-01 resolved).
 * Use Database['public']['Tables']['trips']['Update'] etc. directly.
 */

import type { Database } from './database.types';

// Re-export the Database type helper for convenience
export type { Database };

// ---------------------------------------------------------------------------
// Typed helpers for the Supabase JS client's RPC call (returns Json generically)
// ---------------------------------------------------------------------------

/** Generic RPC client — used when the generated client doesn't know the RPC signature. */
export type SupabaseRpcClient = {
  rpc: (
    fn: string,
    args?: Record<string, unknown>
  ) => Promise<{ data: unknown; error: { message: string } | null }>;
};

// ---------------------------------------------------------------------------
// RPC result shapes — RPCs return Json; cast to these after error checking.
// ---------------------------------------------------------------------------

/** Return shape of the `get_trip_full` RPC. */
export interface GetTripFullResult {
  trip: Record<string, unknown>;
  members: unknown[];
  stats: unknown[];
  eras: unknown[];
  cover_photo: unknown | null;
  error?: string;
}

/** Return shape of the `join_trip_by_code` RPC. */
export interface JoinTripResult {
  trip_id: string;
  error?: string;
}

/** Return shape of the `submit_confession` RPC. */
export interface ConfessionResult {
  success?: boolean;
  error?: string;
}

/** Row shape returned by the `get_nostalgia_moments` RPC. */
export interface NostalgiaRow {
  photo_id: string;
  trip_id: string;
  trip_name: string;
  trip_year: number;
  destination: string | null;
  storage_path: string;
  thumbnail_path: string | null;
  chaos_score: number | null;
  years_ago: number;
  lore_tagline: string | null;
}

/** Row shape returned by the `find_similar_photos` RPC. */
export interface SimilarPhotoRow {
  photo_id: string;
  trip_id: string;
  trip_name: string;
  storage_path: string;
  thumbnail_path: string | null;
  similarity: number;
  trip_year: number;
  destination: string | null;
}

// ---------------------------------------------------------------------------
// list_user_trips RPC — custom pagination function (migration 2026051906)
// ---------------------------------------------------------------------------

/** Arguments for the `list_user_trips` RPC. */
export interface ListUserTripsArgs {
  p_user_id: string;
  p_cursor?: string | null;
  p_limit?: number;
}

/** Row shape returned by `list_user_trips`. Mirrors the SQL function's RETURNS TABLE. */
export interface ListUserTripsRow {
  trip_id: string;
  name: string;
  destination: string | null;
  trip_start_date: string | null;
  trip_end_date: string | null;
  lore_status: string | null;
  chaos_score: number | null;
  member_count: number | null;
  total_photos: number | null;
  tier: string | null;
  created_at: string | null;
  lore_json: unknown;
}

// ---------------------------------------------------------------------------
// claim_lore_generation RPC — atomic claim function (migration 2026051905)
// ---------------------------------------------------------------------------

/** Return values of the `claim_lore_generation` RPC. */
export type ClaimLoreResult = 'claimed' | 'already_processing' | 'forbidden';
